name: "CI Model API"

on:
  push:
    branches: [ model-api ]
    paths:
      - "square-model-inference-api/**"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths:
      - "square-model-inference-api/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  model-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-api-v1"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-model_api-
            ${{ runner.os }}-buildx-

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-model-inference-api/inference_server
          target: test
          load: true
          tags: ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag }}-test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Retrieve Test Reports
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag }}-test
          path: /app/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-model-inference-api/inference_server
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag }}, ${{ steps.prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  model-management:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-management"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-model_api-
            ${{ runner.os }}-buildx-

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-model-inference-api/management_server
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag }}, ${{ steps.prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
